name: Aliyun Docker Image Pusher Production

on:
  push:
    branches: [ master ]

env:
  REPO_TAG: registry.cn-guangzhou.aliyuncs.com/weishuokun/foxglove-ui:release

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Aliyun Docker Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cn-guangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.REPO_TAG }}

